kind: pipeline
name: default

steps:
  - name: deploy code to vs1
    image: plugins/ansible:1
    settings:
      private_key:
        from_secret: ansible_private_key
      playbook: .ansible/deploy.yml
      inventory: .ansible/inventory.yml
      verbose: 4
      ssh_extra_args: -o StrictHostKeyChecking=no
    when:
      event:
      - push
      - tag

  - name: send notification to telegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 393273328
      format: html
      message: >
        {{#success build.status}}
          succeeded build {{build.link}} triggerd by {{commit.link}} from {{commit.author}}
        {{else}}
          failed build {{build.link}} triggerd by {{commit.link}} from {{commit.author}}
        {{/success}}
    when:
      status:
        - success
        - failure
